// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package basego

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInput struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Dni                  string   `protobuf:"bytes,7,opt,name=dni,proto3" json:"dni,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInput) Reset()         { *m = UserInput{} }
func (m *UserInput) String() string { return proto.CompactTextString(m) }
func (*UserInput) ProtoMessage()    {}
func (*UserInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInput.Unmarshal(m, b)
}
func (m *UserInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInput.Marshal(b, m, deterministic)
}
func (m *UserInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInput.Merge(m, src)
}
func (m *UserInput) XXX_Size() int {
	return xxx_messageInfo_UserInput.Size(m)
}
func (m *UserInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInput.DiscardUnknown(m)
}

var xxx_messageInfo_UserInput proto.InternalMessageInfo

func (m *UserInput) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInput) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInput) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInput) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInput) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserInput) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserInput) GetDni() string {
	if m != nil {
		return m.Dni
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserResponse struct {
	User                 *UserInput `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *UserInput {
	if m != nil {
		return m.User
	}
	return nil
}

type UserID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInput)(nil), "basego.UserInput")
	proto.RegisterType((*Response)(nil), "basego.Response")
	proto.RegisterType((*UserResponse)(nil), "basego.UserResponse")
	proto.RegisterType((*UserID)(nil), "basego.UserID")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x71, 0xe2, 0x38, 0xc9, 0xfc, 0x7f, 0x43, 0x2a, 0xb2, 0x10, 0x59, 0x15, 0xd3, 0x42,
	0x57, 0x2e, 0x4d, 0x29, 0x74, 0x9f, 0x40, 0xe9, 0x26, 0x0b, 0x43, 0x0e, 0xa0, 0xa0, 0x21, 0x35,
	0x24, 0x96, 0xd0, 0xc8, 0xe4, 0x64, 0xbd, 0x4b, 0x8f, 0x53, 0x34, 0x8e, 0x4c, 0x4b, 0xbc, 0xf3,
	0x7b, 0xef, 0x7b, 0xe3, 0x91, 0x10, 0x40, 0x43, 0xe8, 0x0a, 0xeb, 0x8c, 0x37, 0x22, 0xdb, 0x2b,
	0xc2, 0x83, 0xc9, 0xbf, 0x12, 0x98, 0xee, 0x08, 0xdd, 0x47, 0x6d, 0x1b, 0x2f, 0x96, 0x30, 0x09,
	0x4c, 0xad, 0x4e, 0x28, 0x93, 0xbb, 0xe4, 0x71, 0x5a, 0x76, 0x3a, 0x64, 0x56, 0x11, 0x9d, 0x8d,
	0xd3, 0x72, 0xd0, 0x66, 0x51, 0x0b, 0x01, 0x29, 0x77, 0x86, 0xec, 0xa7, 0x91, 0x3f, 0x2a, 0xf2,
	0xdb, 0xe0, 0xa7, 0x2d, 0x1f, 0xb5, 0x58, 0xc0, 0xc8, 0x7e, 0x9a, 0x1a, 0xe5, 0x88, 0x83, 0x56,
	0x08, 0x09, 0x63, 0xa5, 0xb5, 0x43, 0x22, 0x99, 0xb1, 0x1f, 0xa5, 0x98, 0xc3, 0x50, 0xd7, 0x95,
	0x1c, 0xb3, 0x1b, 0x3e, 0xf3, 0x7b, 0x98, 0x94, 0x48, 0xd6, 0xd4, 0xc4, 0xbd, 0x13, 0x12, 0xa9,
	0x43, 0x5c, 0x3a, 0xca, 0xfc, 0x15, 0xfe, 0x87, 0xc3, 0x75, 0xe4, 0x03, 0xa4, 0xe1, 0x3c, 0x8c,
	0xfd, 0x5b, 0xdd, 0x16, 0xed, 0x25, 0x14, 0xdd, 0x05, 0x94, 0x1c, 0xe7, 0x12, 0x32, 0xb6, 0x36,
	0x62, 0x06, 0x83, 0x4a, 0x5f, 0xa6, 0x0e, 0x2a, 0xbd, 0xfa, 0x4e, 0x60, 0xb2, 0x76, 0x8d, 0x0e,
	0xb1, 0x78, 0x83, 0x9b, 0xb5, 0x43, 0xe5, 0x71, 0x8b, 0x67, 0x36, 0xae, 0x07, 0x2e, 0x17, 0xbf,
	0xad, 0x6e, 0x8f, 0x02, 0x60, 0x83, 0x47, 0xf4, 0xc8, 0xb5, 0xd9, 0x9f, 0xda, 0x66, 0x39, 0x8f,
	0xba, 0xe3, 0x9f, 0x01, 0x76, 0x56, 0xab, 0x0b, 0xdf, 0xf3, 0x9b, 0xeb, 0xca, 0x13, 0x8c, 0xdf,
	0xd1, 0xf7, 0xce, 0xef, 0xdd, 0x69, 0x9f, 0xf1, 0xc3, 0x78, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x73, 0x5f, 0xf4, 0xd8, 0x26, 0x02, 0x00, 0x00,
}
